apires/urls.py
#import de Django
from django.urls import path

#view
from .userView import *

urlpatterns = [
	#path('user/loginres/', vista_login_API.as_view(), name="login"),
    path('user/login/', vista_login_API.as_view(), name="login"),
    path('user/historia/', vista_historia_API.as_view(), name="historia"),
  
]

carspro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carsapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carsapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Persona(models.Model):
	nombre=models.CharField(max_length=100)
	apellido=models.CharField(max_length=100)
	identificacion=models.DecimalField(max_digits=12, decimal_places=0)
	telefono=models.DecimalField(max_digits=12, decimal_places=0)
	direccion=models.CharField(max_length=100)
	preguntasegu=models.CharField(max_length=100)
	respuesta=models.CharField(max_length=50)
	usuario=models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
	def __str__(self):
		return str(self.identificacion)

class Carro(models.Model):
	modelo=models.CharField(max_length=15)
	ciudad=models.CharField(max_length=30)
	marca=models.CharField(max_length=100)
	placa=models.CharField(max_length=10, unique=True)
	idalarma=models.CharField(max_length=20, unique=True)
	persona=models.ForeignKey(Persona, on_delete=models.CASCADE)
	def __str__(self):
		return self.placa

class Contacto(models.Model):
	opciones=(('bb','ballenas jorbadas'),('ba', 'ballenas de lo frio'), ('ga', 'gallina'), ('sa','sapo'),)
	nombres=models.CharField(max_length=100)
	apellidos=models.CharField(max_length=100)
	telefono=models.DecimalField(max_digits=12, decimal_places=0)
	email=models.EmailField(max_length=200)
	asunto=models.CharField(max_length=2, choices=opciones)
	mensaje=models.CharField(max_length=200)
	def __str__(self):
		return str(self.identificacion)

class Notificacion(models.Model):
	notif=models.CharField(max_length=100)
	posicion=models.DecimalField(max_digits=30, decimal_places=12)
	idala=models.CharField(max_length=20)

class Tokenfirebase(models.Model):
	token=models.CharField(max_length=500)
	usuario=models.OneToOneField(User, on_delete=models.CASCADE)
	def __str__(self):
		return self.username;
		

carsapp/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User


class agregar_persona_form(forms.ModelForm):
	class Meta:
		model=Persona
		fields='__all__'
		widgets = {
			'nombre':forms.TextInput(attrs={'class':'form-control'}),
			'apellido':forms.TextInput(attrs={'class':'form-control'}),
			'identificacion':forms.TextInput(attrs={'class':'form-control'}),
			'telefono' :forms.TextInput(attrs={'class':'form-control'}),
			'direccion':forms.TextInput(attrs={'class':'form-control'}),
			'preguntasegu' : forms.TextInput(attrs={'class':'form-control '}),
			'respuesta': forms.TextInput(attrs={'class':'form-control '})
		}

class agregar_carro_form(forms.ModelForm):
	class Meta:
		model=Carro
		fields='__all__'
		'''	modelo=forms.CharField(widget= forms.TextInput())
		ciudad=forms.CharField(widget=forms.TextInput())
		marca=forms.CharField(widget= forms.TextInput())
		placa=forms.CharField(widget=forms.TextInput())
		idalarma=forms.CharField(widget= forms.TextInput())
		persona=forms.ModelChoiceField(queryset=Persona.objects.all())'''
		widgets = {
			'modelo':forms.TextInput(attrs={'class':'form-control '}),
			'ciudad':forms.TextInput(attrs={'class':'form-control'}),
			'marca':forms.TextInput(attrs={'class':'form-control'}),
			'placa' :forms.TextInput(attrs={'class':'form-control'}),
			'idalarma':forms.TextInput(attrs={'class':'form-control'}),
			'persona' : forms.Select(attrs={'class':'js-example-basic-single form-control'})
		}

class confirmar_user_form(forms.Form):
	identificacion=forms.CharField(widget= forms.TextInput(attrs={'tipe': 'number','placeholder':'Identificacion'}))
	respuesta=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Respuesta'}))

	def clean_respuesta(self):
		
		respuesta=self.cleaned_data['respuesta']
		identificacion=self.cleaned_data['identificacion']
		if Persona.objects.filter(identificacion=identificacion).exists():
			ide=Persona.objects.get(identificacion=identificacion)
			if ide.respuesta== respuesta:
				pass
			else:
				raise forms.ValidationError('respuesta erronea')
			if ide.usuario:
				raise forms.ValidationError('ya tiene usuario creado')
			else:
				pass
		else:
			raise forms.ValidationError('no se encuentra registrado')


class login_form(forms.Form):
	
	usuario = forms.CharField(widget= forms.TextInput(attrs={'class':'form-control','placeholder':'Nombre user'}))
	clave = forms.CharField(widget= forms.PasswordInput(render_value=False, attrs={'class':'form-control', 'placeholder':'Contraseña'}))
	

class register_form(forms.Form):
	username = forms.CharField(widget = forms.TextInput(attrs={'placeholder':'Nombre user'}))
	email = forms.EmailField(widget = forms.TextInput(attrs={'placeholder':'Email'}))
	password1 = forms.CharField(label = 'Password', widget=forms.PasswordInput(render_value=False, attrs={'placeholder':'Contraseña'}))
	password2 = forms.CharField(label = 'Confirmar Password', widget=forms.PasswordInput(render_value=False, attrs={'placeholder':'Contraseña'}))
	


	def clean_username(self):
		username=self.cleaned_data['username']
		try:
			u=User.objects.get(username=username)
		except  User.DoesNotExist:
			return username
		raise forms.ValidationError('Nombre de user ya existe')

	def clean_email(self):

		email=self.cleaned_data['email']
		try:
			email=User.objects.get(email=email)
		except User.DoesNotExist:
			return email
		raise forms.ValidationError('email ya existe')

	def clean_password2(self):
		password1=self.cleaned_data['password1']
		password2=self.cleaned_data['password2']
		if password1==password2:
			pass
		else:
			raise forms.ValidationError('Password no coinciden')

class contacto_form(forms.ModelForm):   # se utiliza forms.ModelForm cuando se quiere trabajar con el formulario del diseño
	class Meta:                         #de los modelos de la ase de datos
		model=Contacto
		fields='__all__'
	
class dispositivos_form(forms.Form):
	idalarma = forms.CharField(widget = forms.TextInput())

class notificacion_form(forms.ModelForm):
	class Meta:
		model=Notificacion
		fields='__all__'




	

templates/agregar_persona.html
{% extends 'basenav.html'%}
{%load static%} 
{% block titulo%}

{% endblock %}

{%block contenido%}

<section class="conteniAGRE">
	<h2 class="text-center" style="color: white">AGREGAR PERSONA</h2>
	<form action="" method="POST" id="idform">
	{% csrf_token%}
	<!--{{formulario.as_p}}-->
	
		<section class="sombraAGRE">	
		      	 <div class="form-row ">
					 <div class="form-group  col-md-6">
				    	<label for="id_nombre">Nombre</label>
				    	{{formulario.nombre}}
				     </div>
				      <div class="form-group  col-md-6">
				    	<label for="id_apellido">Apellido</label>
				    	{{formulario.apellido}}
				     </div>

				     <div class="form-group  col-md-6">
				    	<label for="id_identificacion">Identificacion</label>
				    	{{formulario.identificacion}}
				     </div>
					 <div class="form-group  col-md-6">
				    	<label for="id_telefono">Telefono</label>
				    	{{formulario.telefono}}
				    </div>
				     <div class="form-group  col-md-6">
				    	<label for="id_direccion">Direccion</label>
				    	{{formulario.direccion}}
				    </div>
				    <div class="form-group  col-md-6">
				    	<label for="id_preguntasegu">Pregunta de seguridad</label>
				        {{formulario.preguntasegu}}
				    </div>
				    <div class="form-group  col-md-6">
				    	<label  for="id_respuesta">Respuesta</label>
				        {{formulario.respuesta}}
				    </div>
				    <br/>
				    <p class="form-group col-md-6">
				    	TODOS LOS CAMPOS SON OBLIGATORIOS</p>
				    
				    
				 </div>
			    <hr/>
			    <input type="submit" class="btn btn-primary col-md-2" value="Agregar Persona" id="btn-dos">
			   </div>	
		</section> 	
	
	</form>	
</section>	
	{% block javascript%}
		<!--<script src="{% static "js/s.js" %}"></script>-->

	{% endblock javascript%}
{% endblock %}	

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	 <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
	<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css/sporta.css" rel="stylesheet" type="text/css">
	<title>
		
		{% block titulo%}
			
		{%endblock%}	
	</title>

</head>
<body>
	{%block contenido%}
	{%endblock%}

	 <script src="/static/js/jquery.js"></script>
     <script src="/static/js/bootstrap.min.js"></script>
     
</body>
</html>

templates/basenav.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
  <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css">
  <link rel="stylesheet" type="text/css" href="/static/css/sporta.css">
  <!--<link type="text/css" href="/static/css/select2.min.css" rel="stylesheet" />-->
  {% block titulo%}
  
  {% endblock %}
  
</head>
<body>

  
   <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #2962ff;">
          <a class="navbar-brand" href="{% url 'vista_inicio'%}"> 
          <!--<span> <img src="/static/ima/a.jpg" width="250" height="40" alt=""> </span>--> 
          <h2>CARSAFE</h2> 
            </a>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'inicio_superuser'%}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'vista_agregar_persona'%}">Add Register<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'vista_agregar_carro'%}">Add car<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'vista_lista_persona'%}">Person List<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'vista_lista_carro'%}">Car List<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'vista_logout'%}">Logout</a>
            </li>

          </ul>
        </div>
      </nav>
      
      {%block contenido%}
    
      {%endblock%}

    <script src="/static/js/jquery.js"></script>
      <script src="/static/js/bootstrap.js"></script>
      <script src="/static/js/spinner.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

     {% block javascript%}
 
 
      {% endblock %}
</body>
</html>

templates/confirmar_user.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 , shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Validar información</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/static/css/myestilo.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="/static/css/sporta.css">
</head>
<body>
	<section class="card container col-sm col-md col-lg text-center" style="width: 20rem;">
		<img src="/static/ima/ees.png" class="card-img-tp" alt="12">
		<p class="parra">Validar información. 
			 Por favor llena todos los campos
		</p>
		
		<form method="POST" action="">
			{% csrf_token %}
			<label for="identificacion">Identificación</label>
				{{formulario.identificacion}}
			<label for="respuesta">Respuesta</label>
				{{formulario.respuesta}}
			{% if formulario.errors %}
				<div class="alert alert-danger" role="alert">
				<a>
					{{formulario.identificacion.errors}}
					{{formulario.respuesta.errors}}
				</a>
				</div>	
			{% endif %}

			<div>
				<input type="submit" value= "validar">
			</div>
		</form>
			

		
	</section>




    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
</body>
</html>

templates/confirmar_user1.html
{% extends 'base.html'%}
{% block titulo%}
	validar informacion 
{% endblock %}
{%block contenido%}
	<div class="col-sm col-md col-lg form-signin text-center">
	<form action="" method="POST" enctype= "multipart/form-data" class="container ">
		<h2>Validar Información</h2>
	{% csrf_token%} 
	<!--{{formulario.as_p}}-->
	<div>
		<label for="identificacion" >Identificación</label>
		{{formulario.identificacion}}
		
	</div>
	<div>
			<label for="respuesta">Respuesta</label>
			{{formulario.respuesta}}

			
	</div>
	{% if formulario.errors %}
	<div class="alert alert-danger" role="alert">
		<a >
			{{formulario.identificacion.errors}}
		    {{formulario.respuesta.errors}}
		</a>
		

		
	</div>
	{% endif %}

	<input type="submit" value= "validar">		
	</form>	
	</div>
{% endblock %}

templates/contacto.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1 , shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title id ="ti">contactanos</title>
	<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css/sporta.css" rel="stylesheet" type="text/css">
</head>
<body class="">
  <header>
        <div class="col-sm col-md col-lg">
        <nav aria-label="breadcrumb ">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active">
                    <a href="{% url 'vista_inicio' %}">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Contacto</li>
            </ol>
        </nav>
    </div>
  </header>


  <section class="container card col-sm col-md col-lg sombra1" style="width: 20rem;">
      <h4>Envianos un mensaje</h4>
      <hr/>
    <form method="POST" action="" class="">

        {% csrf_token %}
        {{ formulario.as_p }}
        <div class="text-center">
        <input type="submit" value="Enviar">
        </div>
        
          <!-- <p class="parra1">
              Email: carsafe@gmsil.com <br>
              Telefono: 6467123 <br>
              WhatsApp: 3124562344 <br>
           </p>-->
        
    </form>
    
    </section>
  <!--  <section class="container card col-sm col-md col-lg sombra2" style="width: 18rem;">
      <p>
        email: carsafe@gmsil.com
        telefono: 6467123
        WhatsApp: 3124562344
      </p>
      
    </section>-->
  <script src="/static/js/jquery.js"></script>
  <script src="/static/js/bootstrap.js"></script>
</body>
</html>

templates/contacto2.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
	<title>login</title>
	<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css/sporta.css" rel="stylesheet" type="text/css">
</head>
 <body >
 	Send me a copy of this message
HTML
<!-- Default form contact -->
<form class="text-center border border-light p-5 container" action="#!">

    <p class="h4 mb-4">Contact us</p>

    <!-- Name -->
    <input type="text" id="defaultContactFormName" class="form-control mb-4" placeholder="Name">

    <!-- Email -->
    <input type="email" id="defaultContactFormEmail" class="form-control mb-4" placeholder="E-mail">

    <!-- Subject -->
    <label>Subject</label>
    <select class="browser-default custom-select mb-4">
        <option value="" disabled>Choose option</option>
        <option value="1" selected>Feedback</option>
        <option value="2">Report a bug</option>
        <option value="3">Feature request</option>
        <option value="4">Feature request</option>
    </select>

    <!-- Message -->
    <div class="form-group">
        <textarea class="form-control rounded-0" id="exampleFormControlTextarea2" rows="3" placeholder="Message"></textarea>
    </div>

    <!-- Copy -->
    <div class="custom-control custom-checkbox mb-4">
        <input type="checkbox" class="custom-control-input" id="defaultContactFormCopy">
        <label class="custom-control-label" for="defaultContactFormCopy">Send me a copy of this message</label>
    </div>

    <!-- Send button -->
    <button class="btn btn-info" type="submit">Send</button>

</form>
<!-- Default form contact -->



	<script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.js"></script>
 </body>
</html>

templates/inicio1.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
      <title>no</title>
      <!-- <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
      <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %} "> -->
      <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css">
      <link rel="stylesheet" type="text/css" href="/static/css/pos.css">

    </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #2962ff;">
        <a class="navbar-brand" href="{% url 'vista_inicio'%}"> 
        <span> <img src="/static/ima/a.jpg" width="250" height="40" alt=""> </span> 
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link " href="{% url 'vista_inicio'%}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vista_login'%}">Iniciar seccion</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vista_mensaje'%}">Contacto</a>
            </li>

          </ul>
        </div>
      </nav> 
      <div>
         
         <img  class="imag" >


      </div>
      <div class="container text-center textobien">
      
       <h1>BIENVENIDOS A CARSAFE</h1> 
       <h4>SISTEMAS DE ALARMA PARA VEHICULOS, CON NOTIFICACIÓN AL SMARTPHONE</h4>
      </div> 

      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>

      <h1>alarma con sigfox</h1>
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.js"></script>
   
  </body>
</html>

templates/lista_persona.html
{% extends 'basenav.html'  %}
{%load static%}
{% block titulo %}

{% endblock %}
{% block contenido %}
	<section class="conteniAGREli">
 		{% csrf_token %}
	    <div>
		<table class="table table-striped col-sm col-md col-lg">
			<h3 class="text-center">LISTA PERSONAS</h3>
		       	
        </div>
		<thead>
			<tr>
				<th scope="col">id</th>
				<th scope="col">nombre</th>
				<th scope="col">apellido</th>
				<th scope="col">identificacion</th>
				<!--<th scope="col">email</th>-->
				<th scope="col">telefono</th>
				<th scope="col">direccion</th>
				<th scope="col">pregunta de seguridad</th>
				<th scope="col">respuesta</th>
			</tr>
		</thead>
		<tbody>
			{% for p in lista%}
				<tr>
					<td >{{p.id}}</td>
					<td>{{p.nombre}}</td>
					<td>{{p.apellido}}</td>
					<td>{{p.identificacion}}</td>
					<!--<td>{{p.email}}</td>-->
					<td>{{p.telefono}}</td>
					<td>{{p.direccion}}</td>
					<td>{{p.preguntasegu}}</td>
					<td>{{p.respuesta}}</td>
					<td> 
						<!--<a class="btn btn-primary " id="btn-mostrar" href="{% url 'vista_eliminar_persona' id_Persona=p.id%}" disabled> eliminar registro</a> -->
				
						<button class="btn btn-primary btn-mostrar" onclick="borrar_usu({{p.id}},{{p.identificacion}})"> eliminar registro</button> 
					</td>
				</tr>


			{% endfor%}
		</tbody>

	    </table>
	    </div>
	 </section>   


	   {% block javascript%}
	   
	   <!--<script src="{% static "js/s.js" %}"></script>
	    <script src="{% static "js/mod.js" %}"></script>-->
	  <script src="{% static "js/sweetalert2@9.js" %}"></script>
	  <script type="text/javascript">
	  function nose(id, nombres){
	  	console.log('nose');
	  	/*var urlba='eliminar_persona';*/
	  	var u='https://carsafelowydavo.herokuapp.com/eliminar_persona/'
	  	var id_Persona=id;
	  	/*window.href = urlba+'/'+id_Persona;*/
	  	$.ajax({
		url: u+id_Persona,
		success: function(respuesta) {
			console.log('respuesta ok');

			 Swal.fire(
			      'Deleted!',
			      'El registro '+nombres +' ha sido eliminado.',
			      'success'
			     
			).then((confirm)=>{
				if(confirm.value==true)
				window.location.reload();

			});

			
			
		},
		error: function() {
	        console.log("No se ha podido obtener la información");
	    }
	    
		});

	  }	
	  function borrar_usu(id, nombres) 
	  	{ 
	  		console.log('consola'+id);
	  		Swal.fire({
			  title: 'Estas seguro?',
			  text: "Quieres eliminar el registro identificado: "+nombres,
			  icon: 'warning',
			  backdrop: 'rgba(0,10,123,0.4)',
			  showCancelButton: true,
			  confirmButtonColor: '#3085d6',
			  cancelButtonColor: '#d33',
			  confirmButtonText: 'Aceptar'
				}).then((result) => {
			  if (result.value) {
			   nose(id, nombres);
			   
			  }
			  else{

			  }
			});
	  	}


	  </script>
      {% endblock %}
{% endblock %}

templates/lista_token.html
{% extends 'basenav.html'  %}
{% block titulo %}

{% endblock %}
{% block contenido %}
 
	    <div>
		<table class="table table-striped col-sm col-md col-lg">
	
		<thead>
			<tr>
				<th scope="col">id</th>
				<th scope="col">token</th>
				<th scope="col">idusuario</th>
			</tr>
		</thead>
		<tbody>
			{% for p in listatoken%}
				<tr>
					<td>{{p.id}}</td>
					<td>{{p.token}}</td>
					<td>{{p.usuario}}</td>
				</tr>
			{% endfor%}
		</tbody>

	    </table>
	    </div>
{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <title></title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/static/css/sporta.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="col-sm col-md col-lg">
        <nav aria-label="breadcrumb ">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active">
                    <a href="{% url 'vista_inicio' %}">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Login</li>
            </ol>
        </nav>
    </div>
 <!--   <div class="col-sm col-md col-lg form-signin">
      
       <form action="" method="POST">
            <div class="text-center">
                <p>Estas registrado inicia secion, de lo contrario <a href="{% url 'vista_confirmar_user' %}">REGISTRATE AQUI</a> </p>
                
            </div>
            {% csrf_token %}
            <div>
                <label for="usuario" >Usuario</label>
                {{formulario.usuario}}
            </div>
            <div>
              <label for="clave">Contraseña</label>
              {{formulario.clave}}
            </div> 
            <h3>{{ msj }}</h3>
            <div class="col-lg col-md col-sm text-center ">
               <button type="submit" class="btn-primary">Login</button>
               <input type="submit" value="Login">
           </div>     

    </div>
     <div class="card">
        <div class="card-body col-sm col-md col-lg container text-center" style="width: 18rem;">
              <div class="text-center">
                <p>Estas registrado inicia sesión, de lo contrario <a href="{% url 'vista_confirmar_user' %}">REGISTRATE AQUI</a> 
              </p>
                
            </div>
            {% csrf_token %}
            <label for="usuario" >Usuario</label>
              {{formulario.usuario}}
            <label for="clave">Contraseña</label>
              {{formulario.clave}}
              <h3>{{ msj }}</h3> 
              <button type="submit" class="btn-primary">Login</button>
              <input type="submit" value="Login">
        </div> 
        <br>
        <br>   
            
       </div> 

      </form>
    </div>-->
<!--------------------formulario con tarjeta------------------------------------------------------------------------->
    <div class="container card text-center col-sm col-md col-lg" style="width: 18rem;">
        <img src="/static/ima/ees.png" class="card-img-tp" alt="">
        <p class="col-sm col-md col-lg parra">Estas registrado inicia secion, de lo contrario <a href="{% url 'vista_confirmar_user' %}">REGISTRATE AQUI</a> </p>
            <form method="POST" action="">
                    {% csrf_token %}
                  <label for="usuario"  >Usuario</label>
                    {{formulario.usuario}}
                  <label for="clave">Contraseña</label>
                    {{formulario.clave}}
                    {% if ban %}
                       <div class="alert alert-danger" role="alert">
                            {{ msj }}
                       </div> 
                     {%endif%}        
                  <button type="submit" class="btn-primary">Login</button>               
            </form>

    </div>

    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

</body>

</html>